### ISSUE TITLE
Build `cuquantum-python` in this repo?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cuquantum-feedstock#16]
Right now, when making a new release, we need to build `cuquantum` first, and then wait some time (a couple of hours in the past) to sync CDN so that we can build `cuquantum-python`. By unifying the conda recipes we can release them at once. We should look into it.

**Comment by leofang** [comment]
Hi @conda-forge/core I am seeing a situation. I am trying to generate `cuquantum-python` in this feedstock so that I can abandon `cuquantum-python-feedstock`. I already bumped the build number, but it seems the CI is unable to upload the packages to `cf-stage`, am I missing any step?
```
copy results:
{
  "errors": [
    "output linux-64/cuquantum-python-22.07.1-py38hca921df_1.tar.bz2 not allowed for conda-forge/cuquantum-feedstock",
    "output linux-64/cuquantum-python-22.07.1-py310hbe3ad0c_1.tar.bz2 not allowed for conda-forge/cuquantum-feedstock",
    "output linux-64/cuquantum-python-22.07.1-py39hcf40d7a_1.tar.bz2 not allowed for conda-forge/cuquantum-feedstock"
  ],
  "valid": {
    "linux-64/cuquantum-python-22.07.1-py38hca921df_1.tar.bz2": false,
    "linux-64/cuquantum-python-22.07.1-py310hbe3ad0c_1.tar.bz2": false,
    "linux-64/cutensornet-1.1.1-h0800d71_0.tar.bz2": true,
    "linux-64/cuquantum-python-22.07.1-py39hcf40d7a_1.tar.bz2": false,
    "linux-64/custatevec-1.1.0-h0800d71_0.tar.bz2": true,
    "linux-64/cuquantum-22.07.1.14-h0bbbad9_1.tar.bz2": true
  },
  "copied": {
    "linux-64/cutensornet-1.1.1-h0800d71_0.tar.bz2": true,
    "linux-64/custatevec-1.1.0-h0800d71_0.tar.bz2": true,
    "linux-64/cuquantum-22.07.1.14-h0bbbad9_1.tar.bz2": true,
    "linux-64/cuquantum-python-22.07.1-py38hca921df_1.tar.bz2": false,
    "linux-64/cuquantum-python-22.07.1-py310hbe3ad0c_1.tar.bz2": false,
    "linux-64/cuquantum-python-22.07.1-py39hcf40d7a_1.tar.bz2": false
  }
}
Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=613908

**Comment by jakirkham** [comment]
Would do something like this:

* https://github.com/conda-forge/feedstock-outputs/pull/3
* https://github.com/conda-forge/feedstock-outputs/pull/5

**Comment by leofang** [comment]
Thanks @jakirkham 🙏 Done: https://github.com/conda-forge/feedstock-outputs/pull/38

**Comment by leofang** [comment]
I see the uploads succeeded now, closing.
