### ISSUE TITLE
License hyperlink on anaconda.org not working

### ISSUE THREAD

**Issue by leofang** [conda-forge/cuquantum-feedstock#3]
This hyperlink on anaconda.org does not correctly jump to `license_url` set in `meta.yaml`:
<img width="749" alt="截圖 2022-01-05 下午3 21 20" src="https://user-images.githubusercontent.com/5534781/148283799-4826ebdc-25d6-4364-aaad-ca59f1c2087c.png">

**Comment by jakirkham** [comment]
This is similar to the issue we had with `cudatoolkit` ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2 ), but we fixed that one.

@chenghlee, would you be able to help us here? 🙂

**Comment by leofang** [comment]
@chenghlee To follow our observations here and elsewhere, my impression is that when uploading to anaconda.org:
- If the license name is not prefixed by `LicenseRef-`, it uses `license_url` to generate the hyperlink
- Otherwise, it forces to search the license name on OSI

And this setting is only run the first time a package is uploaded; subsequent changes/uploads do not re-trigger this check.

**Comment by jakirkham** [comment]
IIRC that use to be the case, but it was fixed to update with new packages. So there may be a different issue going on here (though feel free to correct me Cheng 🙂)

**Comment by leofang** [comment]
The license url redirects work now, but point to wrong places, will follow up in #46.
