### ISSUE TITLE
`license_url` doesn't work?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuquantum-feedstock#46]
When trying to the visit the `license_url` from the recipe, the page appears not to be available

https://github.com/conda-forge/cuquantum-feedstock/blob/497efce876c8963f1f528f035c89bf65485a0ff1/recipe/meta.yaml#L306

<hr>

<img width="1840" alt="Screenshot 2023-08-02 at 11 50 16 AM" src="https://github.com/conda-forge/cuquantum-feedstock/assets/3019665/d611b8aa-26d5-4a85-ba44-53eddc6d87b3">

**Comment by leofang** [comment]
Right, I recently added support for versioned docs, and the old urls are now invalidated. Will fix in the next update 🙂 Thanks, John!

**Comment by leofang** [comment]
My bad, I only updated `docs_url` not `license_rul` 🤯

**Comment by leofang** [comment]
I'll fix it when the next migrator comes (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4834)... 😅

**Comment by leofang** [comment]
We fixed the license urls, but it seems they no longer get rendered on anaconda.org. There's no more hyperlinking. I am fine with this "fix" from Anaconda, just wanna raise awareness.

**Comment by leofang** [comment]
xref: https://github.com/conda/infrastructure/discussions/739#discussioncomment-7363975
