### ISSUE TITLE
Package request: cuQuantum 24.11.0.21 update

### ISSUE THREAD

**Issue by mtjrider** [conda-forge/cuquantum-feedstock#66]
### Package name

cuquantum, cuquantum-python

### Package version

24.11.0.21

### Package availability

Currently available:

1. PyPI
2. NVIDIA DevZone

### Package is not available

- [x] The package is not available on conda-forge.

### No previous issues or open PRs

- [x] No previous issue exists and no PR has been opened.

**Comment by jakirkham** [comment]
Transferred to the cuQuantum feedstock as this regards updating an existing feedstock
